// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ftp/get/anon": {
            "post": {
                "description": "Подключается к FTP-серверу как anonymous и скачивает указанный файл",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FTP"
                ],
                "summary": "Скачать файл с FTP (анонимный доступ)",
                "parameters": [
                    {
                        "description": "Адрес сервера и путь к файлу",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetFileAnonymousRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Файл успешно загружен",
                        "schema": {
                            "$ref": "#/definitions/models.FileResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Файл не найден",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        },
        "/api/v1/ftp/get/auth": {
            "post": {
                "description": "Подключается к FTP-серверу с использованием логина и пароля, и скачивает указанный файл",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "FTP"
                ],
                "summary": "Скачать файл с FTP (авторизация)",
                "parameters": [
                    {
                        "description": "Параметры подключения и файл",
                        "name": "input",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.GetFileWithAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Файл успешно загружен",
                        "schema": {
                            "$ref": "#/definitions/models.FileResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный формат запроса",
                        "schema": {
                            "$ref": "#/definitions/swagger.IncorrectFormatError"
                        }
                    },
                    "404": {
                        "description": "Файл не найден",
                        "schema": {
                            "$ref": "#/definitions/swagger.NotFoundError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/swagger.InternalServerError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.FileResponse": {
            "type": "object",
            "properties": {
                "content_base64": {
                    "type": "string",
                    "example": "MQ0KMg0KMw0KdGVzdCBzdWNjZXNzISE="
                },
                "filename": {
                    "type": "string",
                    "example": "test.txt"
                }
            }
        },
        "models.GetFileAnonymousRequest": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "example": "/data/test.txt"
                },
                "host": {
                    "type": "string",
                    "example": "192.168.1.1"
                },
                "port": {
                    "type": "string",
                    "example": "22"
                }
            }
        },
        "models.GetFileWithAuthRequest": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string",
                    "example": "/data/test.txt"
                },
                "host": {
                    "type": "string",
                    "example": "192.168.1.1"
                },
                "password": {
                    "type": "string",
                    "example": "password"
                },
                "port": {
                    "type": "string",
                    "example": "22"
                },
                "username": {
                    "type": "string",
                    "example": "admin"
                }
            }
        },
        "swagger.IncorrectFormatError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 400
                        },
                        "message": {
                            "type": "string",
                            "example": "Неверный формат запроса"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "IncorrectFormatError"
                }
            }
        },
        "swagger.InternalServerError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 500
                        },
                        "message": {
                            "type": "string",
                            "example": "Внутренняя ошибка сервера"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "InternalServerError"
                }
            }
        },
        "swagger.NotFoundError": {
            "type": "object",
            "properties": {
                "response": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "integer",
                            "example": 404
                        },
                        "message": {
                            "type": "string",
                            "example": "Данные не найдены"
                        }
                    }
                },
                "status": {
                    "type": "string",
                    "example": "NotFoundError"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FTP Client API",
	Description:      "API для работы с протоколом FTP",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
